//HintName: DecoWeaver.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace DecoWeaver.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class DecoWeaverInterceptors
    {
        [InterceptsLocation(version: 1, data: "A5UbS1XWAcgcQQfyREJP6BIBAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddScoped&lt;global::DecoWeaver.Sample.IRepository<global::Product>, global::DecoWeaver.Sample.DynamoDbRepository<global::Product>&gt;(IServiceCollection, Func&lt;IServiceProvider, global::DecoWeaver.Sample.DynamoDbRepository<global::Product>&gt;)</summary>
        internal static IServiceCollection AddScoped_0<TService, TImplementation>(this IServiceCollection services, Func<IServiceProvider, TImplementation> implementationFactory)
            where TService : class
            where TImplementation : class, TService
        {
            // Register the undecorated implementation as a keyed service with factory
            var key = DecoratorKeys.For(typeof(global::DecoWeaver.Sample.IRepository<global::Product>), typeof(global::DecoWeaver.Sample.DynamoDbRepository<global::Product>));
            services.AddKeyedScoped<global::DecoWeaver.Sample.IRepository<global::Product>>(key, (sp, _) => (global::DecoWeaver.Sample.IRepository<global::Product>)implementationFactory(sp));

            // Register factory that applies decorators
            services.AddScoped<global::DecoWeaver.Sample.IRepository<global::Product>>(sp =>
            {
                var current = (global::DecoWeaver.Sample.IRepository<global::Product>)sp.GetRequiredKeyedService<global::DecoWeaver.Sample.IRepository<global::Product>>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::DecoWeaver.Sample.IRepository<global::Product>)DecoratorFactory.Create(sp, typeof(global::DecoWeaver.Sample.IRepository<global::Product>), typeof(global::DecoWeaver.Sample.CachingRepository<>), current);
                current = (global::DecoWeaver.Sample.IRepository<global::Product>)DecoratorFactory.Create(sp, typeof(global::DecoWeaver.Sample.IRepository<global::Product>), typeof(global::DecoWeaver.Sample.LoggingRepository<>), current);
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }
        }

        private static class DecoratorFactory
        {
            public static object Create(IServiceProvider sp, Type serviceType, Type decoratorOpenOrClosed, object inner)
            {
                var closedType = CloseIfNeeded(decoratorOpenOrClosed, serviceType);
                return ActivatorUtilities.CreateInstance(sp, closedType, inner)!;
            }

            private static Type CloseIfNeeded(Type t, Type serviceType)
            {
                if (!t.IsGenericTypeDefinition) return t;
                var args = serviceType.IsGenericType ? serviceType.GetGenericArguments() : Type.EmptyTypes;
                return t.MakeGenericType(args);
            }
        }

    }
}
