//HintName: Sculptor.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace Sculptor.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class SculptorInterceptors
    {
        [InterceptsLocation(version: 1, data: "qza3Lgb9jPDSGBGWlEE/EbQAAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddSingleton&lt;global::Sculptor.Sample.IUserService, global::Sculptor.Sample.UserService&gt;(IServiceCollection)</summary>
        internal static IServiceCollection AddSingleton_0<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, TService
        {
            // Register the undecorated implementation as a keyed service
            var key = DecoratorKeys.For(typeof(global::Sculptor.Sample.IUserService), typeof(global::Sculptor.Sample.UserService));
            services.AddKeyedSingleton<global::Sculptor.Sample.IUserService, global::Sculptor.Sample.UserService>(key);

            // Register factory that applies decorators
            services.AddSingleton<global::Sculptor.Sample.IUserService>(sp =>
            {
                var current = (global::Sculptor.Sample.IUserService)sp.GetRequiredKeyedService<global::Sculptor.Sample.IUserService>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::Sculptor.Sample.IUserService)DecoratorFactory.Create(sp, typeof(global::Sculptor.Sample.IUserService), typeof(global::Sculptor.Sample.UserLoggingDecorator), current);
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }
        }

        private static class DecoratorFactory
        {
            public static object Create(IServiceProvider sp, Type serviceType, Type decoratorOpenOrClosed, object inner)
            {
                var closedType = CloseIfNeeded(decoratorOpenOrClosed, serviceType);
                return ActivatorUtilities.CreateInstance(sp, closedType, inner)!;
            }

            private static Type CloseIfNeeded(Type t, Type serviceType)
            {
                if (!t.IsGenericTypeDefinition) return t;
                var args = serviceType.IsGenericType ? serviceType.GetGenericArguments() : Type.EmptyTypes;
                return t.MakeGenericType(args);
            }
        }

    }
}
