//HintName: Sculptor.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace Sculptor.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class SculptorInterceptors
    {
        [InterceptsLocation(version: 1, data: "e38EDFiLyMJFTRxAsJ8UwssBAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddScoped&lt;global::Sculptor.Sample.IRepository<Order>, global::Sculptor.Sample.DynamoDbRepository<Order>&gt;(IServiceCollection)</summary>
        internal static IServiceCollection AddScoped_0<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, TService
        {
            // Register the undecorated implementation as a keyed service
            var key = DecoratorKeys.For(typeof(global::Sculptor.Sample.IRepository<Order>), typeof(global::Sculptor.Sample.DynamoDbRepository<Order>));
            services.AddKeyedScoped<global::Sculptor.Sample.IRepository<Order>, global::Sculptor.Sample.DynamoDbRepository<Order>>(key);

            // Register factory that applies decorators
            services.AddScoped<global::Sculptor.Sample.IRepository<Order>>(sp =>
            {
                var current = (global::Sculptor.Sample.IRepository<Order>)sp.GetRequiredKeyedService<global::Sculptor.Sample.IRepository<Order>>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::Sculptor.Sample.IRepository<Order>)DecoratorFactory.Create(sp, typeof(global::Sculptor.Sample.IRepository<Order>), typeof(global::Sculptor.Sample.CachingRepository<>), current);
                return current;
            });
            return services;
        }

        [InterceptsLocation(version: 1, data: "e38EDFiLyMJFTRxAsJ8UwoUBAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddScoped&lt;global::Sculptor.Sample.IRepository<Customer>, global::Sculptor.Sample.DynamoDbRepository<Customer>&gt;(IServiceCollection)</summary>
        internal static IServiceCollection AddScoped_1<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, TService
        {
            // Register the undecorated implementation as a keyed service
            var key = DecoratorKeys.For(typeof(global::Sculptor.Sample.IRepository<Customer>), typeof(global::Sculptor.Sample.DynamoDbRepository<Customer>));
            services.AddKeyedScoped<global::Sculptor.Sample.IRepository<Customer>, global::Sculptor.Sample.DynamoDbRepository<Customer>>(key);

            // Register factory that applies decorators
            services.AddScoped<global::Sculptor.Sample.IRepository<Customer>>(sp =>
            {
                var current = (global::Sculptor.Sample.IRepository<Customer>)sp.GetRequiredKeyedService<global::Sculptor.Sample.IRepository<Customer>>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::Sculptor.Sample.IRepository<Customer>)DecoratorFactory.Create(sp, typeof(global::Sculptor.Sample.IRepository<Customer>), typeof(global::Sculptor.Sample.CachingRepository<>), current);
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }
        }

        private static class DecoratorFactory
        {
            public static object Create(IServiceProvider sp, Type serviceType, Type decoratorOpenOrClosed, object inner)
            {
                var closedType = CloseIfNeeded(decoratorOpenOrClosed, serviceType);
                return ActivatorUtilities.CreateInstance(sp, closedType, inner)!;
            }

            private static Type CloseIfNeeded(Type t, Type serviceType)
            {
                if (!t.IsGenericTypeDefinition) return t;
                var args = serviceType.IsGenericType ? serviceType.GetGenericArguments() : Type.EmptyTypes;
                return t.MakeGenericType(args);
            }
        }

    }
}
